//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OzyParkAdmin.Domain.Reportes.Pivoted {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PivotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PivotResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OzyParkAdmin.Domain.Reportes.Pivoted.PivotResources", typeof(PivotResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of {0}.
        /// </summary>
        internal static string AverageAggregatorFactoryHeaderFormat {
            get {
                return ResourceManager.GetString("AverageAggregatorFactoryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string CountAggregatorFactoryHeaderFormat {
            get {
                return ResourceManager.GetString("CountAggregatorFactoryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateName {
            get {
                return ResourceManager.GetString("DateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string DayName {
            get {
                return ResourceManager.GetString("DayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LongMonth.
        /// </summary>
        internal static string LongMonthName {
            get {
                return ResourceManager.GetString("LongMonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Max of {0}.
        /// </summary>
        internal static string MaxAggregatorFactoryHeaderFormat {
            get {
                return ResourceManager.GetString("MaxAggregatorFactoryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min of {0}.
        /// </summary>
        internal static string MinAggregatorFactoryHeaderFormat {
            get {
                return ResourceManager.GetString("MinAggregatorFactoryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string MonthName {
            get {
                return ResourceManager.GetString("MonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        internal static string QuarterName {
            get {
                return ResourceManager.GetString("QuarterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShortMonth.
        /// </summary>
        internal static string ShortMonthName {
            get {
                return ResourceManager.GetString("ShortMonthName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of {0}.
        /// </summary>
        internal static string SumAggregatorFactoryHeaderFormat {
            get {
                return ResourceManager.GetString("SumAggregatorFactoryHeaderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string YearName {
            get {
                return ResourceManager.GetString("YearName", resourceCulture);
            }
        }
    }
}
